server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/josephmn/service-configuration.git
        clone-on-start: true
        #searchPaths: msv-customer