server:
  port: ${SERVER_PORT:8888}
spring:
  application:
    name: config-server
    version: "@project.version@"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/josephmn/service-configuration.git
          default-label: main  # o master, según tu rama principal
          # search-paths: config  # carpeta donde están tus archivos de configuración
#          clone-on-start: true
#          force-pull: true
#          timeout: 5
#          refresh-rate: 30  # Tiempo en segundos para buscar cambios
  output:
    ansi:
      enabled: ALWAYS
      #-Dspring.output.ansi.enabled=always
created:
  by: Joseph Magallanes
  email: josephcarlos.jcmn@gmail.com
  date: 2025-08-01
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health,webhook
